/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.list.app;


public class App {
    public static void main(String[] args) {
      ListLinked<String> lista =new ListLinked<String>();
      lista.add("Lucas");
      lista.add("Jorge"); 
      lista.add("Pedro");
      lista.add("Manuel");
      lista.add("Santiago");
      lista.add("felipe");

      System.out.println(lista.showData());
    }
}
